### ISSUE TITLE
Microsoft Edge Browser and message event

### ISSUE THREAD

**Issue by stevilyu** [kmamykin/aws-mqtt#2]
It looks like the message event is not being fired on the Microsoft Edge Browser, even after successfully connecting and subscribing to a topic.  Browser version is Microsoft Edge 38.14393.0.0.

Works great otherwise, on Firefox and Chrome.

Edit: Looks like the packet for subscribe gets sent but no suback is returned.

**Comment by stevilyu** [comment]
I did a little bit more digging to inspect the web socket traffic and it looks like the subscribe packet is never being sent by the browser.  I followed the debugger all the way down to the mqtt-packet module writing to the stream.  Looks like on the next tick when the stream gets uncorked, the message gets sent in Chrome, but not in Edge.  Any thoughts or insights would be greatly appreciated!

**Comment by kmamykin** [comment]
Hey @stevilyu ,
Thanks for a digging in to this issue, very helpful!

`isBrowserSocket` is defined here:
https://github.com/kmamykin/mqtt-websocket-stream/blob/master/src/utils.js#L19

```
export const isBrowserSocket = (socket) => {
  return socket.send.length === 1 // send is sync in browser and async with length 3 on server using 'ws' module
}
```
which was kind of a hack. The idea is we need to differentiate between a browser version of WebSocket and a server/node.js version of WebSocket. While both implementations should be compatible (ha!) ws.WebSocket.prototype.send takes 3 parameters (and is async function with a callback) and browser's WebSocket.prototype.send takes 1 parameter, and is sync.

I see that https://msdn.microsoft.com/library/Hh994652 has it that `send` takes only 1 argument, so my guess is that socket.send.length returns 0 on MS Edge. May be due to https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/110711/

I dont have Ms Edge installed, if you can figure out a better way to check if WebSocket instance is browser's or ws's let me know, or better yet submit a pull request against https://github.com/kmamykin/mqtt-websocket-stream

**Comment by stevilyu** [comment]
I actually just ended up changing that conditional statement to make it work:

```
var isBrowserSocket = exports.isBrowserSocket = function isBrowserSocket(socket) {
  return socket.send.length != 3; // send is sync in browser and async with length 3 on server using 'ws' module
};```

Probably not the best approach, but worked in a pinch!
